// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: lattice.proto

package latticev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LatticeAudit_AuditStream_FullMethodName = "/lattice.v1.LatticeAudit/AuditStream"
)

// LatticeAuditClient is the client API for LatticeAudit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LatticeAudit is the bidirectional streaming interface used by FlashAudit
// clients and workers. The preferred production payload is FlatBuffers
// (see proto/lattice.fbs), but structured protobuf messages are kept for
// debugging and early integration.
type LatticeAuditClient interface {
	AuditStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuditRequest, AuditResponse], error)
}

type latticeAuditClient struct {
	cc grpc.ClientConnInterface
}

func NewLatticeAuditClient(cc grpc.ClientConnInterface) LatticeAuditClient {
	return &latticeAuditClient{cc}
}

func (c *latticeAuditClient) AuditStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuditRequest, AuditResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LatticeAudit_ServiceDesc.Streams[0], LatticeAudit_AuditStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditRequest, AuditResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LatticeAudit_AuditStreamClient = grpc.BidiStreamingClient[AuditRequest, AuditResponse]

// LatticeAuditServer is the server API for LatticeAudit service.
// All implementations must embed UnimplementedLatticeAuditServer
// for forward compatibility.
//
// LatticeAudit is the bidirectional streaming interface used by FlashAudit
// clients and workers. The preferred production payload is FlatBuffers
// (see proto/lattice.fbs), but structured protobuf messages are kept for
// debugging and early integration.
type LatticeAuditServer interface {
	AuditStream(grpc.BidiStreamingServer[AuditRequest, AuditResponse]) error
	mustEmbedUnimplementedLatticeAuditServer()
}

// UnimplementedLatticeAuditServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLatticeAuditServer struct{}

func (UnimplementedLatticeAuditServer) AuditStream(grpc.BidiStreamingServer[AuditRequest, AuditResponse]) error {
	return status.Error(codes.Unimplemented, "method AuditStream not implemented")
}
func (UnimplementedLatticeAuditServer) mustEmbedUnimplementedLatticeAuditServer() {}
func (UnimplementedLatticeAuditServer) testEmbeddedByValue()                      {}

// UnsafeLatticeAuditServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LatticeAuditServer will
// result in compilation errors.
type UnsafeLatticeAuditServer interface {
	mustEmbedUnimplementedLatticeAuditServer()
}

func RegisterLatticeAuditServer(s grpc.ServiceRegistrar, srv LatticeAuditServer) {
	// If the following call panics, it indicates UnimplementedLatticeAuditServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LatticeAudit_ServiceDesc, srv)
}

func _LatticeAudit_AuditStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LatticeAuditServer).AuditStream(&grpc.GenericServerStream[AuditRequest, AuditResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LatticeAudit_AuditStreamServer = grpc.BidiStreamingServer[AuditRequest, AuditResponse]

// LatticeAudit_ServiceDesc is the grpc.ServiceDesc for LatticeAudit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LatticeAudit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lattice.v1.LatticeAudit",
	HandlerType: (*LatticeAuditServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuditStream",
			Handler:       _LatticeAudit_AuditStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lattice.proto",
}
