// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: lattice.proto

package latticev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlKind int32

const (
	ControlKind_CONTROL_KIND_UNSPECIFIED ControlKind = 0
	ControlKind_START                    ControlKind = 1
	ControlKind_PAUSE                    ControlKind = 2
	ControlKind_RESUME                   ControlKind = 3
	ControlKind_CANCEL                   ControlKind = 4
)

// Enum value maps for ControlKind.
var (
	ControlKind_name = map[int32]string{
		0: "CONTROL_KIND_UNSPECIFIED",
		1: "START",
		2: "PAUSE",
		3: "RESUME",
		4: "CANCEL",
	}
	ControlKind_value = map[string]int32{
		"CONTROL_KIND_UNSPECIFIED": 0,
		"START":                    1,
		"PAUSE":                    2,
		"RESUME":                   3,
		"CANCEL":                   4,
	}
)

func (x ControlKind) Enum() *ControlKind {
	p := new(ControlKind)
	*p = x
	return p
}

func (x ControlKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lattice_proto_enumTypes[0].Descriptor()
}

func (ControlKind) Type() protoreflect.EnumType {
	return &file_lattice_proto_enumTypes[0]
}

func (x ControlKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlKind.Descriptor instead.
func (ControlKind) EnumDescriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{0}
}

type AuditRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Traceparent string                 `protobuf:"bytes,16,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Baggage     string                 `protobuf:"bytes,17,opt,name=baggage,proto3" json:"baggage,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AuditRequest_HashBatch
	//	*AuditRequest_Control
	//	*AuditRequest_Flatbuf
	Payload       isAuditRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_lattice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRequest) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *AuditRequest) GetBaggage() string {
	if x != nil {
		return x.Baggage
	}
	return ""
}

func (x *AuditRequest) GetPayload() isAuditRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuditRequest) GetHashBatch() *HashBatch {
	if x != nil {
		if x, ok := x.Payload.(*AuditRequest_HashBatch); ok {
			return x.HashBatch
		}
	}
	return nil
}

func (x *AuditRequest) GetControl() *ControlMessage {
	if x != nil {
		if x, ok := x.Payload.(*AuditRequest_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *AuditRequest) GetFlatbuf() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AuditRequest_Flatbuf); ok {
			return x.Flatbuf
		}
	}
	return nil
}

type isAuditRequest_Payload interface {
	isAuditRequest_Payload()
}

type AuditRequest_HashBatch struct {
	HashBatch *HashBatch `protobuf:"bytes,1,opt,name=hash_batch,json=hashBatch,proto3,oneof"`
}

type AuditRequest_Control struct {
	Control *ControlMessage `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

type AuditRequest_Flatbuf struct {
	// FlatBuffers-encoded lattice.fb.AuditRequest (preferred for production).
	Flatbuf []byte `protobuf:"bytes,15,opt,name=flatbuf,proto3,oneof"`
}

func (*AuditRequest_HashBatch) isAuditRequest_Payload() {}

func (*AuditRequest_Control) isAuditRequest_Payload() {}

func (*AuditRequest_Flatbuf) isAuditRequest_Payload() {}

type AuditResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Traceparent string                 `protobuf:"bytes,16,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Baggage     string                 `protobuf:"bytes,17,opt,name=baggage,proto3" json:"baggage,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AuditResponse_CrackedHash
	//	*AuditResponse_Status
	//	*AuditResponse_Error
	//	*AuditResponse_Flatbuf
	Payload       isAuditResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_lattice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{1}
}

func (x *AuditResponse) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *AuditResponse) GetBaggage() string {
	if x != nil {
		return x.Baggage
	}
	return ""
}

func (x *AuditResponse) GetPayload() isAuditResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuditResponse) GetCrackedHash() *CrackedHash {
	if x != nil {
		if x, ok := x.Payload.(*AuditResponse_CrackedHash); ok {
			return x.CrackedHash
		}
	}
	return nil
}

func (x *AuditResponse) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Payload.(*AuditResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AuditResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*AuditResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AuditResponse) GetFlatbuf() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AuditResponse_Flatbuf); ok {
			return x.Flatbuf
		}
	}
	return nil
}

type isAuditResponse_Payload interface {
	isAuditResponse_Payload()
}

type AuditResponse_CrackedHash struct {
	CrackedHash *CrackedHash `protobuf:"bytes,1,opt,name=cracked_hash,json=crackedHash,proto3,oneof"`
}

type AuditResponse_Status struct {
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type AuditResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type AuditResponse_Flatbuf struct {
	// FlatBuffers-encoded lattice.fb.AuditResponse (preferred for production).
	Flatbuf []byte `protobuf:"bytes,15,opt,name=flatbuf,proto3,oneof"`
}

func (*AuditResponse_CrackedHash) isAuditResponse_Payload() {}

func (*AuditResponse_Status) isAuditResponse_Payload() {}

func (*AuditResponse_Error) isAuditResponse_Payload() {}

func (*AuditResponse_Flatbuf) isAuditResponse_Payload() {}

type HashBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each entry must be exactly 16 bytes (raw NTLM hash).
	RawHashes     [][]byte `protobuf:"bytes,1,rep,name=raw_hashes,json=rawHashes,proto3" json:"raw_hashes,omitempty"`
	BatchId       string   `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	SentUnixMs    uint64   `protobuf:"varint,3,opt,name=sent_unix_ms,json=sentUnixMs,proto3" json:"sent_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashBatch) Reset() {
	*x = HashBatch{}
	mi := &file_lattice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashBatch) ProtoMessage() {}

func (x *HashBatch) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashBatch.ProtoReflect.Descriptor instead.
func (*HashBatch) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{2}
}

func (x *HashBatch) GetRawHashes() [][]byte {
	if x != nil {
		return x.RawHashes
	}
	return nil
}

func (x *HashBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *HashBatch) GetSentUnixMs() uint64 {
	if x != nil {
		return x.SentUnixMs
	}
	return 0
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ControlKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=lattice.v1.ControlKind" json:"kind,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BatchId       string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_lattice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetKind() ControlKind {
	if x != nil {
		return x.Kind
	}
	return ControlKind_CONTROL_KIND_UNSPECIFIED
}

func (x *ControlMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ControlMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ControlMessage) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type CrackedHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw 16-byte NTLM hash that was cracked.
	OriginalHash  []byte `protobuf:"bytes,1,opt,name=original_hash,json=originalHash,proto3" json:"original_hash,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Plaintext     string `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	ChainInfo     uint64 `protobuf:"varint,4,opt,name=chain_info,json=chainInfo,proto3" json:"chain_info,omitempty"`
	BatchId       string `protobuf:"bytes,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrackedHash) Reset() {
	*x = CrackedHash{}
	mi := &file_lattice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrackedHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrackedHash) ProtoMessage() {}

func (x *CrackedHash) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrackedHash.ProtoReflect.Descriptor instead.
func (*CrackedHash) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{4}
}

func (x *CrackedHash) GetOriginalHash() []byte {
	if x != nil {
		return x.OriginalHash
	}
	return nil
}

func (x *CrackedHash) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CrackedHash) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *CrackedHash) GetChainInfo() uint64 {
	if x != nil {
		return x.ChainInfo
	}
	return 0
}

func (x *CrackedHash) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type Status struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RateHashesPerSec float64                `protobuf:"fixed64,3,opt,name=rate_hashes_per_sec,json=rateHashesPerSec,proto3" json:"rate_hashes_per_sec,omitempty"`
	Processed        uint64                 `protobuf:"varint,4,opt,name=processed,proto3" json:"processed,omitempty"`
	Cracked          uint64                 `protobuf:"varint,5,opt,name=cracked,proto3" json:"cracked,omitempty"`
	InFlight         uint64                 `protobuf:"varint,6,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	TimestampUnixMs  uint64                 `protobuf:"varint,7,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_lattice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{5}
}

func (x *Status) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Status) GetRateHashesPerSec() float64 {
	if x != nil {
		return x.RateHashesPerSec
	}
	return 0
}

func (x *Status) GetProcessed() uint64 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *Status) GetCracked() uint64 {
	if x != nil {
		return x.Cracked
	}
	return 0
}

func (x *Status) GetInFlight() uint64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *Status) GetTimestampUnixMs() uint64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	BatchId       string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_lattice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_lattice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_lattice_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Error) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_lattice_proto protoreflect.FileDescriptor

const file_lattice_proto_rawDesc = "" +
	"\n" +
	"\rlattice.proto\x12\n" +
	"lattice.v1\"\xe1\x01\n" +
	"\fAuditRequest\x12 \n" +
	"\vtraceparent\x18\x10 \x01(\tR\vtraceparent\x12\x18\n" +
	"\abaggage\x18\x11 \x01(\tR\abaggage\x126\n" +
	"\n" +
	"hash_batch\x18\x01 \x01(\v2\x15.lattice.v1.HashBatchH\x00R\thashBatch\x126\n" +
	"\acontrol\x18\x02 \x01(\v2\x1a.lattice.v1.ControlMessageH\x00R\acontrol\x12\x1a\n" +
	"\aflatbuf\x18\x0f \x01(\fH\x00R\aflatbufB\t\n" +
	"\apayload\"\x89\x02\n" +
	"\rAuditResponse\x12 \n" +
	"\vtraceparent\x18\x10 \x01(\tR\vtraceparent\x12\x18\n" +
	"\abaggage\x18\x11 \x01(\tR\abaggage\x12<\n" +
	"\fcracked_hash\x18\x01 \x01(\v2\x17.lattice.v1.CrackedHashH\x00R\vcrackedHash\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x12.lattice.v1.StatusH\x00R\x06status\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x11.lattice.v1.ErrorH\x00R\x05error\x12\x1a\n" +
	"\aflatbuf\x18\x0f \x01(\fH\x00R\aflatbufB\t\n" +
	"\apayload\"g\n" +
	"\tHashBatch\x12\x1d\n" +
	"\n" +
	"raw_hashes\x18\x01 \x03(\fR\trawHashes\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12 \n" +
	"\fsent_unix_ms\x18\x03 \x01(\x04R\n" +
	"sentUnixMs\"\xf3\x01\n" +
	"\x0eControlMessage\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.lattice.v1.ControlKindR\x04kind\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.lattice.v1.ControlMessage.MetadataEntryR\bmetadata\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\vCrackedHash\x12#\n" +
	"\roriginal_hash\x18\x01 \x01(\fR\foriginalHash\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1c\n" +
	"\tplaintext\x18\x03 \x01(\tR\tplaintext\x12\x1d\n" +
	"\n" +
	"chain_info\x18\x04 \x01(\x04R\tchainInfo\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\tR\abatchId\"\xe9\x01\n" +
	"\x06Status\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x13rate_hashes_per_sec\x18\x03 \x01(\x01R\x10rateHashesPerSec\x12\x1c\n" +
	"\tprocessed\x18\x04 \x01(\x04R\tprocessed\x12\x18\n" +
	"\acracked\x18\x05 \x01(\x04R\acracked\x12\x1b\n" +
	"\tin_flight\x18\x06 \x01(\x04R\binFlight\x12*\n" +
	"\x11timestamp_unix_ms\x18\a \x01(\x04R\x0ftimestampUnixMs\"j\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId*Y\n" +
	"\vControlKind\x12\x1c\n" +
	"\x18CONTROL_KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\t\n" +
	"\x05PAUSE\x10\x02\x12\n" +
	"\n" +
	"\x06RESUME\x10\x03\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x042V\n" +
	"\fLatticeAudit\x12F\n" +
	"\vAuditStream\x12\x18.lattice.v1.AuditRequest\x1a\x19.lattice.v1.AuditResponse(\x010\x01B;Z9github.com/VishwaJaya01/lattice/proto/latticev1;latticev1b\x06proto3"

var (
	file_lattice_proto_rawDescOnce sync.Once
	file_lattice_proto_rawDescData []byte
)

func file_lattice_proto_rawDescGZIP() []byte {
	file_lattice_proto_rawDescOnce.Do(func() {
		file_lattice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lattice_proto_rawDesc), len(file_lattice_proto_rawDesc)))
	})
	return file_lattice_proto_rawDescData
}

var file_lattice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lattice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lattice_proto_goTypes = []any{
	(ControlKind)(0),       // 0: lattice.v1.ControlKind
	(*AuditRequest)(nil),   // 1: lattice.v1.AuditRequest
	(*AuditResponse)(nil),  // 2: lattice.v1.AuditResponse
	(*HashBatch)(nil),      // 3: lattice.v1.HashBatch
	(*ControlMessage)(nil), // 4: lattice.v1.ControlMessage
	(*CrackedHash)(nil),    // 5: lattice.v1.CrackedHash
	(*Status)(nil),         // 6: lattice.v1.Status
	(*Error)(nil),          // 7: lattice.v1.Error
	nil,                    // 8: lattice.v1.ControlMessage.MetadataEntry
}
var file_lattice_proto_depIdxs = []int32{
	3, // 0: lattice.v1.AuditRequest.hash_batch:type_name -> lattice.v1.HashBatch
	4, // 1: lattice.v1.AuditRequest.control:type_name -> lattice.v1.ControlMessage
	5, // 2: lattice.v1.AuditResponse.cracked_hash:type_name -> lattice.v1.CrackedHash
	6, // 3: lattice.v1.AuditResponse.status:type_name -> lattice.v1.Status
	7, // 4: lattice.v1.AuditResponse.error:type_name -> lattice.v1.Error
	0, // 5: lattice.v1.ControlMessage.kind:type_name -> lattice.v1.ControlKind
	8, // 6: lattice.v1.ControlMessage.metadata:type_name -> lattice.v1.ControlMessage.MetadataEntry
	1, // 7: lattice.v1.LatticeAudit.AuditStream:input_type -> lattice.v1.AuditRequest
	2, // 8: lattice.v1.LatticeAudit.AuditStream:output_type -> lattice.v1.AuditResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_lattice_proto_init() }
func file_lattice_proto_init() {
	if File_lattice_proto != nil {
		return
	}
	file_lattice_proto_msgTypes[0].OneofWrappers = []any{
		(*AuditRequest_HashBatch)(nil),
		(*AuditRequest_Control)(nil),
		(*AuditRequest_Flatbuf)(nil),
	}
	file_lattice_proto_msgTypes[1].OneofWrappers = []any{
		(*AuditResponse_CrackedHash)(nil),
		(*AuditResponse_Status)(nil),
		(*AuditResponse_Error)(nil),
		(*AuditResponse_Flatbuf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lattice_proto_rawDesc), len(file_lattice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lattice_proto_goTypes,
		DependencyIndexes: file_lattice_proto_depIdxs,
		EnumInfos:         file_lattice_proto_enumTypes,
		MessageInfos:      file_lattice_proto_msgTypes,
	}.Build()
	File_lattice_proto = out.File
	file_lattice_proto_goTypes = nil
	file_lattice_proto_depIdxs = nil
}
